package com.gamified.stocksimulator.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * User Entity Class - Represents a user in the stock simulator system
 * 
 * This entity is mapped to the 'users' table in MySQL database.
 * Each user has a unique username, email, and their own portfolio/balance.
 * 
 * Annotations explained:
 *   @Entity - Marks this class as a JPA entity to be persisted in database
 *   @Table - Specifies the database table name for this entity
 *   @Id - Marks this field as the primary key
 *   @GeneratedValue - Auto-generates the ID value using database auto-increment
 *   @Column - Specifies column properties like name, nullable, unique constraints
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {
    
    /**
     * Unique identifier for the user
     * Auto-generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;
    
    /**
     * Username - Must be unique and cannot be null
     * Used for login and identification
     */
    @Column(nullable = false, unique = true, length = 50)
    private String username;
    
    /**
     * User's email address - Must be unique
     * Used for communication and account recovery
     */
    @Column(nullable = false, unique = true, length = 100)
    private String email;
    
    /**
     * Encrypted password - Never stored in plain text for security
     * Should be hashed using bcrypt or similar algorithm
     */
    @Column(nullable = false, length = 255)
    private String password;
    
    /**
     * Current account balance in USD
     * Represents the cash available for trading
     */
    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal balance;
    
    /**
     * Initial balance given at account creation
     * Used to calculate profit/loss percentage
     */
    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal initialBalance;
    
    /**
     * Account status - Active or Inactive
     * Used to disable accounts without deleting them
     */
    @Column(nullable = false)
    private Boolean isActive = true;
    
    /**
     * Timestamp when the user account was created
     * Auto-set when the user is first saved
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp of the last update to the user account
     * Updated automatically whenever the user is modified
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;
    
    /**
     * PrePersist method - Called automatically before user is saved to database
     * Initializes timestamps
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    /**
     * PreUpdate method - Called automatically before user is updated in database
     * Updates the last modified timestamp
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
